spring:
  logging:
    config: src/main/resources/logback.xml
  application:
    name: FUZE Enterprise Application
  profiles:
    active: dev
  swagger2:
    title: FUZE API
    description: FUZE API
    version: 1.1
    base-package: com.fuze.bcp.enterprise.controller
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    exchange: fuze-exchange
    routingKey-b: business-routingKey
    routingKey-l: log-routingKey
    routingKey-m: message-routingKey

dubbo:
  zookeeper:
    registry:
      address: 127.0.0.1:2181
      protocol: zookeeper


banner:
  charset: UTF-8

server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8


