spring:
  logging:
    config: @logbackpath@
  application:
    name: FUZE Web Application
  profiles:
    active: @profileActive@
  swagger2:
    title: FUZE API
    description: FUZE API
    version: 1.1
    base-package: com.fuze.bcp.web.controller
  http:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  rabbitmq:
      host: @rabbitmq.host@
      port: @rabbitmq.port@
      username: @rabbitmq.username@
      password: @rabbitmq.password@
      exchange: @rabbitmq.exchange@
      routingKey-b: @rabbitmq.routingKey-b@
      routingKey-l: @rabbitmq.routingKey-l@
      routingKey-m: @rabbitmq.routingKey-m@

dubbo:
  zookeeper:
    registry:
      address: @fuze.bcp.dubbo.zookeeper.registry.address@
      protocol: @fuze.bcp.dubbo.zookeeper.registry.protocol@

banner:
  charset: UTF-8

server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

web:
  websocket:
     url: @fuze.bcp.websocket.url@
