spring:
  logging:
    config: bcp-html/src/main/resources/logback.xml
  application:
    name: FUZE Web Application
  profiles:
    active: dev
  swagger2:
    title: FUZE API
    description: FUZE API
    version: 1.1
    base-package: com.fuze.bcp.web.controller
  http:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      exchange: fuze-exchange
      routingKey-b: business-routingKey
      routingKey-l: log-routingKey
      routingKey-m: message-routingKey

dubbo:
  zookeeper:
    registry:
      address: 127.0.0.1:2181
      protocol: zookeeper

banner:
  charset: UTF-8

server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

web:
  websocket:
     url: localhost:8083
