spring:
  logging:
    config: src/main/resources/logback.xml
  application:
    name: FUZE Pad Application
  profiles:
    active: release
  swagger2:
    title: FUZE API
    description: FUZE API
    version: 1.1
    base-package: com.fuze.bcp.pad.controller
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: 172.16.2.14
    port: 5672
    username: guest
    password: fuzefenqi998
    exchange: fuze-exchange
    routingKey-b: business-routingKey
    routingKey-l: log-routingKey
    routingKey-m: message-routingKey

dubbo:
  zookeeper:
    registry:
      address: 172.16.2.8:2181,172.16.2.9:2181,172.16.2.10:2181
      protocol: zookeeper


banner:
  charset: UTF-8

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8


